version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html:ro
    depends_on:
      - phpfpm
    networks:
      - webnet

  phpfpm:
    build: ./php-fpm
    image: php-fpm
    volumes:
      - ./www:/var/www/html:ro
    depends_on:
      - mysql
    networks:
      - webnet

  mysql:
    image: mysql:8
    volumes:
      - ./mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
      MYSQL_USER: webdb_user
      MYSQL_PASSWORD: webdb_pass
    networks:
      - webnet

networks:
  webnet: